"""extend audit log fields

Revision ID: e026fb199153
Revises: 7b7dd79d9dac
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'e026fb199153'
down_revision: Union[str, Sequence[str], None] = '7b7dd79d9dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('resource', sa.String(length=128), nullable=True))
    op.add_column('audit_logs', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_column('audit_logs', 'description')
    op.drop_column('audit_logs', 'resource')
    # ### end Alembic commands ###
