"""extend asset fields and rename asset name

Revision ID: f1fc5988e164
Revises: 4baebd79fe68
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'f1fc5988e164'
down_revision: Union[str, Sequence[str], None] = '4baebd79fe68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_name', sa.String(length=128), nullable=False))
    op.add_column('assets', sa.Column('os_info', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.create_index(op.f('ix_assets_asset_name'), 'assets', ['asset_name'], unique=False)
    op.drop_column('assets', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('name', sa.VARCHAR(length=128), nullable=False))
    op.drop_index(op.f('ix_assets_asset_name'), table_name='assets')
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.drop_column('assets', 'os_info')
    op.drop_column('assets', 'asset_name')
    # ### end Alembic commands ###
