<template><div><div class="page-title"><div><div class="eyebrow">SECURITY REPORTING</div><h2>安全报告</h2></div><el-button type="primary" :loading="generating" @click="generate">生成报告</el-button></div><div v-loading="loading" class="table-wrap section-card"><el-table :data="reports"><el-table-column prop="report_name" label="报告名称"/><el-table-column prop="generated_at" label="生成时间"/><el-table-column prop="asset_count" label="资产"/><el-table-column prop="vulnerability_count" label="漏洞"/><el-table-column prop="high_risk_vulnerability_count" label="高危漏洞"/><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" @click="view(row)">查看</el-button><el-button link type="success" @click="download(row)">PDF</el-button></template></el-table-column></el-table><el-empty v-if="!loading&&!reports.length" description="暂无报告，请生成第一份安全报告"/></div><el-drawer v-model="visible" title="安全报告详情" size="620px"><div v-if="selected"><el-row :gutter="12"><el-col :span="8"><el-statistic title="资产总数" :value="selected.asset_count"/></el-col><el-col :span="8"><el-statistic title="漏洞总数" :value="selected.vulnerability_count"/></el-col><el-col :span="8"><el-statistic title="高危漏洞" :value="selected.high_risk_vulnerability_count"/></el-col></el-row><el-divider/><h3>风险等级分布</h3><el-descriptions :column="2" border><el-descriptions-item v-for="(value,key) in selected.risk_distribution" :key="key" :label="String(key)">{{value}}</el-descriptions-item></el-descriptions><h3>整改建议</h3><el-alert v-for="item in selected.recommendations" :key="item" :title="item" type="warning" show-icon class="section-card"/><el-button type="primary" class="section-card" @click="openHtml(selected)">打开 HTML 报告</el-button></div></el-drawer></div></template>
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import client from "../api/client";
import type { SecurityReport } from "../api/types";

const reports = ref<SecurityReport[]>([]), selected = ref<SecurityReport | null>(null), visible = ref(false), loading = ref(false), generating = ref(false);
const formatShanghai = (value: string) => new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "medium", timeZone: "Asia/Shanghai", hour12: false }).format(new Date(value));
const shanghaiDate = (value: Date) => new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Shanghai" }).format(value);
const load = async () => { loading.value = true; try { reports.value = (await client.get("/reports")).data; } catch { reports.value = []; } finally { loading.value = false; } };
const generate = async () => { generating.value = true; try { const end = new Date(), start = new Date(end.getTime() - 30 * 86400000); await client.post("/reports", { report_name: `安全运营报告 ${shanghaiDate(end)}`, period_start: start.toISOString(), period_end: end.toISOString() }); ElMessage.success("报告已生成"); await load(); } catch { ElMessage.error("报告生成失败，请确认管理员权限"); } finally { generating.value = false; } };
const view = (row: SecurityReport) => { selected.value = row; visible.value = true; };
const saveBlob = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
const download = async (row: SecurityReport) => { try { const response = await client.get(`/reports/${row.id}/pdf`, { responseType: "blob" }); saveBlob(response.data, `security-report-${row.id}.pdf`); } catch { ElMessage.error("PDF下载失败"); } };
const openHtml = async (row: SecurityReport) => { try { const response = await client.get(`/reports/${row.id}/html`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); window.open(url, "_blank"); } catch { ElMessage.error("HTML报告打开失败"); } };
onMounted(load);
</script>
