<template>
  <div>
    <div class="page-title"><div><div class="eyebrow">AUTOMATED INSPECTION</div><h2>自动化巡检</h2></div><el-button type="primary" @click="openCreate">新建计划</el-button></div>
    <el-alert title="计划任务由 Celery Beat 调度，Worker 在后台执行授权范围内的 Nmap 扫描。" type="warning" show-icon class="section-card" />
    <div v-loading="loading" class="table-wrap section-card"><el-table :data="items"><el-table-column prop="task_name" label="任务名称"/><el-table-column prop="target" label="目标资产"/><el-table-column label="执行周期"><template #default="{row}">{{ cycleLabel(row) }}</template></el-table-column><el-table-column prop="next_run_at" label="下次执行"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="tagType(row.status)">{{ label(row.status) }}</el-tag></template></el-table-column><el-table-column prop="last_run_at" label="最近执行"/><el-table-column label="操作" width="290"><template #default="{row}"><el-button link type="primary" @click="history(row)">执行历史</el-button><el-button link @click="edit(row)">编辑</el-button><el-button link type="success" @click="toggle(row)">{{row.status==='disabled'?'启用':'停用'}}</el-button><el-button link type="warning" :disabled="row.status==='running'||row.status==='disabled'" @click="run(row)">立即执行</el-button></template></el-table-column></el-table><el-empty v-if="!loading&&!items.length" description="暂无自动化巡检计划"/></div>
    <el-dialog v-model="visible" :title="editing ? '编辑计划' : '新建计划'" width="500px"><el-form :model="form" label-width="100px"><el-form-item label="任务名称"><el-input v-model="form.task_name"/></el-form-item><el-form-item label="目标资产"><el-input v-model="form.target" placeholder="例如 127.0.0.1"/></el-form-item><el-form-item label="扫描类型"><el-select v-model="form.scan_type"><el-option label="端口扫描" value="port_scan"/></el-select></el-form-item><el-form-item label="执行周期"><el-select v-model="form.schedule_type"><el-option label="一次性" value="once"/><el-option label="每天 02:00" value="daily"/><el-option label="每周一 02:00" value="weekly"/><el-option label="自定义 Cron" value="cron"/></el-select></el-form-item><el-form-item v-if="form.schedule_type==='cron'" label="Cron 表达式"><el-input v-model="form.cron_expression" placeholder="0 2 * * *"/></el-form-item><el-form-item v-if="form.schedule_type==='once'" label="执行时间"><el-date-picker v-model="form.execute_at" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
    <el-drawer v-model="historyVisible" title="执行历史" size="620px"><el-timeline><el-timeline-item v-for="item in histories" :key="item.id" :timestamp="item.created_at" :type="timelineType(item.status)"><div class="history-item"><strong>{{label(item.status)}}</strong><span>{{item.result_summary||item.error_message||'暂无摘要'}}</span><small>扫描任务 #{{item.id}}</small></div></el-timeline-item></el-timeline><el-empty v-if="!histories.length" description="暂无执行记录"/></el-drawer>
  </div>
</template>
<script setup lang="ts">
import { onMounted, onUnmounted, reactive, ref } from "vue"; import { ElMessage, ElMessageBox } from "element-plus"; import client from "../api/client"; import type { Scan, ScanSchedule } from "../api/types";
const items=ref<ScanSchedule[]>([]),histories=ref<Scan[]>([]),loading=ref(true),saving=ref(false),visible=ref(false),historyVisible=ref(false),editing=ref(false),editId=ref(0);let timer:number|undefined;const form=reactive({task_name:"",target:"",scan_type:"port_scan",schedule_type:"once",execute_at:"",cron_expression:""});
const load=async()=>{loading.value=true;try{items.value=(await client.get("/scan-schedules")).data;}catch{items.value=[];}finally{loading.value=false;}};const reset=()=>Object.assign(form,{task_name:"",target:"",scan_type:"port_scan",schedule_type:"once",execute_at:"",cron_expression:""});const openCreate=()=>{editing.value=false;reset();visible.value=true};const edit=(row:ScanSchedule)=>{editing.value=true;editId.value=row.id;Object.assign(form,row);visible.value=true};const save=async()=>{saving.value=true;try{if(editing.value)await client.patch(`/scan-schedules/${editId.value}`,form);else await client.post("/scan-schedules",{...form,execute_at:form.execute_at||null});ElMessage.success("计划已保存");visible.value=false;await load();}catch{ElMessage.error("保存失败，请检查周期和目标");}finally{saving.value=false;}};const toggle=async(row:ScanSchedule)=>{try{await client.patch(`/scan-schedules/${row.id}`,{status:row.status==='disabled'?'pending':'disabled'});ElMessage.success(row.status==='disabled'?"计划已启用":"计划已停用");await load();}catch{ElMessage.error("状态更新失败");}};const run=async(row:ScanSchedule)=>{try{await client.post(`/scan-schedules/${row.id}/run`);ElMessage.success("已提交后台执行");await load();}catch{ElMessage.error("提交失败");}};const history=async(row:ScanSchedule)=>{try{histories.value=(await client.get(`/scan-schedules/${row.id}/history`)).data;historyVisible.value=true;}catch{ElMessage.error("无法读取执行历史");}};const cycleLabel=(row:ScanSchedule)=>({once:"一次性",daily:"每天 02:00",weekly:"每周一 02:00",cron:`Cron ${row.cron_expression||""}`}[row.schedule_type]||row.schedule_type);const label=(s:string)=>({pending:"等待中",running:"执行中",completed:"完成",failed:"失败",disabled:"已停用"}[s]||s);const tagType=(s:string)=>s==='completed'?'success':s==='failed'?'danger':s==='running'?'warning':s==='disabled'?'info':'';const timelineType=(s:string)=>s==='completed'?'success':s==='failed'?'danger':s==='running'?'warning':'primary';onMounted(()=>{load();timer=window.setInterval(load,5000)});onUnmounted(()=>{if(timer)window.clearInterval(timer)});
</script>
